TRUNCATE TABLE product

INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Adidas Cap', N'Adidas', N'Clothing')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Adidas Hoodie', N'Adidas', N'Clothing')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Apple - Northern Spy', N'NULL', N'Grocery')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Beans - Yellow', N'NULL', N'Grocery')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Dell XPS Notebook', N'Dell', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Doilies - 8, Paper', N'NULL', N'Grocery')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Galaxy Note 10', N'Samsung', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Galaxy S10', N'Samsung', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Galaxy S10+', N'Samsung', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Galaxy S20', N'Samsung', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Galaxy S20+', N'Samsung', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Galaxy S9', N'Samsung', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Galaxy S9+', N'Samsung', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Glass Cup', N'IKEA', N'Tableware')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Huawei P40', N'Huawei', N'Electronics')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'iphon', N'G2000', N'Clothing')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'iPhone X', N'Apple', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'iPhone XR', N'Apple', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'iPhone XS', N'Apple', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'JBL speaker', N'JBL', N'Electronics')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Lenovo Thinkpad', N'Lenovo', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'LG Washing Machine', N'LG', N'Electronics')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Men AIRism Crew Neck T-Shirt', N'Uniqlo', N'Clothing')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Microsoft Surface Pro 7', N'Microsoft', N'Electronics')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Poplin Shirt', N'G2000', N'Clothing')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Poster', N'IKEA', N'Decoration')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Pureboost RBL Shoes', N'Adidas', N'Footwear')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Pureboost Shoes', N'Adidas', N'Footwear')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Samsung Galaxy Tab S5', N'Samsung', N'Electronic Gadgets')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Samsung LCD TV', N'Samsung', N'Electronics')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Sealy Posturepedic Aspire', N'Sealy Posturepedic', N'Furniture')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Soup Campbells Split Pea And Ham', N'NULL', N'Grocery')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Sproutsmustard Cress', N'NULL', N'Grocery')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Squid Ink', N'NULL', N'Grocery')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Stock - Beef, Brown', N'NULL', N'Grocery')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Ultraboost Shoes', N'Adidas', N'Footwear')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Water - Spring Water 500ml', N'NULL', N'Grocery')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Wiberg Cure', N'NULL', N'Grocery')
INSERT [dbo].[product] ([product_name], [maker], [category]) VALUES (N'Wine - Chablis J Moreau Et Fils', N'NULL', N'Grocery')