TRUNCATE table product_in_shop

INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Adidas', N'Adidas Cap', 20.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Royal Sporting House', N'Adidas Cap', 20.0000, 5000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Adidas', N'Adidas Hoodie', 50.0000, 5000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Royal Sporting House', N'Adidas Hoodie', 50.0000, 5000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Challenger', N'Dell XPS Notebook', 1500.0000, 2000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Samsung', N'Galaxy S10', 1000.0000, 2000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Samsung', N'Galaxy S10+', 1100.0000, 2000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Samsung', N'Galaxy S20', 1200.0000, 2000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Samsung', N'Galaxy S20+', 1400.0000, 2000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Samsung', N'Galaxy S9', 900.0000, 2000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Samsung', N'Galaxy S9+', 950.0000, 2000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Samsung', N'Samsung LCD TV',5000.0000, 2000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Samsung', N'Samsung Galaxy Tab S5', 800.0000, 2000)
-- INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Samsung', N'Galaxy Note 10', 1800.0000, 2000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Tesco', N'Glass Cup', 5000.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Walmart', N'Glass Cup', 5000.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Tesco', N'Huawei P40', 999.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Walmart', N'Huawei P40', 1000.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'iStudio', N'iPhone X', 1000.0000, 5000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'iStudio', N'iPhone XR', 1000.0000, 5000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'iStudio', N'iPhone XS', 1200.0000, 5000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Tesco', N'JBL speaker', 5.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Walmart', N'JBL speaker', 5.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Harvey Norman', N'Lenovo Thinkpad', 1300.0000, 5000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Harvey Norman', N'LG Washing Machine', 1900.0000, 2000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Tesco', N'Men AIRism Crew Neck T-Shirt', 20.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Walmart', N'Men AIRism Crew Neck T-Shirt', 5.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Tesco', N'Microsoft Surface Pro 7', 1300.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Walmart', N'Microsoft Surface Pro 7', 1200.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Tesco', N'Poplin Shirt', 5.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Walmart', N'Poplin Shirt', 5.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Tesco', N'Poster', 1.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Adidas', N'Pureboost RBL Shoes', 199.0000, 6000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Adidas', N'Pureboost Shoes', 179.0000, 6000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Challenger', N'Samsung Galaxy Tab S5', 1100.0000, 4000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Harvey Norman', N'Galaxy S20+', 1500.0000, 1000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Harvey Norman', N'Samsung LCD TV', 4000.0000, 1000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Tesco', N'Samsung LCD TV', 4800.0000, 1000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Challenger', N'Samsung LCD TV', 5000.0000, 500)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Tesco', N'Sealy Posturepedic Aspire', 5.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Walmart', N'Sealy Posturepedic Aspire', 5.0000, 10000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Adidas', N'Ultraboost Shoes', 200.0000, 5000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Royal Sporting House', N'Ultraboost Shoes', 200.0000, 5000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Challenger', N'iPhone X', 1000.0000, 5000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Challenger', N'iPhone XR', 1000.0000, 5000)
INSERT [dbo].[product_in_shop] ([shop_name], [product_name], [price_in_shop], [quantity]) VALUES (N'Challenger', N'iPhone XS', 1200.0000, 5000)